version: '3.1'

services:
  app:
    image: 'caldockerrerz/demo:latest'
    build:
      context:  .
    container_name: app
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/yte-intern-application
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=pass
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
      - accessKey=notfound
      - secret=notfound
      - bucketName=abucket
      - region=eu-central-1
      - spring.servlet.multipart.max-request-size=500MB
      - spring.servlet.multipart.max-file-size=500MB


  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: root
      POSTGRES_DB: yte-intern-application
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080