version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: root
      POSTGRES_DB: yte-intern-application
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080